FROM localhost:5000/pg:postgresql

MAINTAINER me

USER postgres

ADD postgresql.conf /etc/postgresql/9.5/main/postgresql.conf

# ADD recovery.conf /var/lib/postgresql/9.5/main/recovery.conf

USER root
