version: '2'

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/24
          ip_range: 172.28.32.0/27
          gateway: 172.28.0.2

services: 
  pg1:
    image: localhost:5000/pg:postgresql
    container_name: pg1
    hostname: pg1
    privileged: true
    build: ./postgresql
    env_file: .env
    environment:
      - ROLE=MASTER

  pg2:
    container_name: pg2
    hostname: pg2
    privileged: true
    image: localhost:5000/pg:postgresql
    build: ./postgresql
    env_file: .env
    environment:
      - ROLE=SLAVE

  pg3:
    container_name: pg3
    hostname: pg3
    privileged: true
    image: localhost:5000/pg:postgresql
    build: ./postgresql
    env_file: .env
    environment:
      - ROLE=SLAVE
