version: '2'

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/24
          ip_range: 172.28.32.0/27
          gateway: 172.28.0.2

services:
  postgresql:
    image: localhost:5000/pg:postgresql
    build: ./postgresql
    entrypoint: /bin/echo 0
 
  postgresql1:
    image: localhost:5000/pg:postgresql1
    container_name: postgresql1
    hostname: postgresql1
    privileged: true
    build: ./postgresql1
    depends_on:
      - postgresql
    env_file: .env
    environment:
      - ROLE=MASTER

  postgresql2:
    container_name: postgresql2
    hostname: postgresql2
    privileged: true
    image: localhost:5000/pg:postgresql2
    build: ./postgresql2
    depends_on:
      - postgresql
    env_file: .env
    environment:
      - ROLE=SLAVE

  postgresql3:
    container_name: postgresql3
    hostname: postgresql3
    privileged: true
    image: localhost:5000/pg:postgresql2
    build: ./postgresql2
    depends_on:
      - postgresql
    env_file: .env
    environment:
      - ROLE=SLAVE
